name: Release
on:
    push:
        branches:
            - 'main'

permissions:
    contents: write
    issues: write
    pull-requests: write
    id-token: write

concurrency: ${{ github.workflow }}-${{github.ref}}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Use PNPM
              uses: pnpm/action-setup@v4
              with:
                  version: 10.4.1

            - name: Use Node.js 18
              uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: 'pnpm'

            - name: Check Commit message
              uses: wagoid/commitlint-github-action@v6
              with:
                  configFile: commitlint.config.ts

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Check formatting
              run: pnpm format

            - name: Lint
              run: pnpm lint

            - name: Test
              run: pnpm test

            - name: Build
              run: pnpm build

            - name: Create Version PR or Publish to NPM
              id: changesets
              uses: changesets/action@v1.4.1
              with:
                  commit: 'chore(release): version packages'
                  title: 'chore(release): version packages'
                  version: node .github/changeset-version.mjs
                  publish: npx changeset publish
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
                  NODE_ENV: 'production'
